const initialBoard = [
  [
    <Piece type="rook" color="black" />,
    <Piece type="knight" color="black" />,
    <Piece type="bishop" color="black" />,
    <Piece type="queen" color="black" />,
    <Piece type="king" color="black" />,
    <Piece type="bishop" color="black" />,
    <Piece type="knight" color="black" />,
    <Piece type="rook" color="black" />,
  ],
  [
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
  ],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
  ],
  [
    <Piece type="rook" color="white" />,
    <Piece type="knight" color="white" />,
    <Piece type="bishop" color="white" />,
    <Piece type="queen" color="white" />,
    <Piece type="king" color="white" />,
    <Piece type="bishop" color="white" />,
    <Piece type="knight" color="white" />,
    <Piece type="rook" color="white" />,
  ],
];

const PromotionBoardTest = [
  [
    <Piece type="rook" color="black" />,
    <Piece type="knight" color="black" />,
    <Piece type="bishop" color="black" />,
    <Piece type="queen" color="black" />,
    <Piece type="king" color="black" />,
    <Piece type="bishop" color="black" />,
    <Piece type="knight" color="black" />,
    null,
  ],
  [
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="white" />,
  ],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
    null,
  ],
  [
    <Piece type="rook" color="white" />,
    <Piece type="knight" color="white" />,
    <Piece type="bishop" color="white" />,
    <Piece type="queen" color="white" />,
    <Piece type="king" color="white" />,
    <Piece type="bishop" color="white" />,
    <Piece type="knight" color="white" />,
    null,
  ],
];

const stalemateBoardTest = [
  [
    null,
    null,
    null,
    <Piece type="king" color="black" />,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    <Piece type="pawn" color="black" />,
    null,
    null,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    <Piece type="king" color="white" />,
    <Piece type="pawn" color="white" />,
    null,
    null,
    null,
  ],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
];

const checkmateBoardTest = [
  [
    <Piece type="rook" color="black" />,
    null,
    <Piece type="bishop" color="black" />,
    <Piece type="queen" color="black" />,
    <Piece type="king" color="black" />,
    <Piece type="bishop" color="black" />,
    null,
    <Piece type="rook" color="black" />,
  ],
  [
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
    null,
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
    <Piece type="pawn" color="black" />,
  ],
  [
    null,
    null,
    <Piece type="knight" color="black" />,
    null,
    null,
    <Piece type="knight" color="black" />,
    null,
    null,
  ],
  [
    null,
    null,
    null,
    null,
    <Piece type="pawn" color="black" />,
    null,
    null,
    <Piece type="queen" color="white" />,
  ],
  [
    null,
    null,
    <Piece type="bishop" color="white" />,
    null,
    <Piece type="pawn" color="white" />,
    null,
    null,
    null,
  ],
  [null, null, null, null, null, null, null, null],
  [
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
    null,
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
    <Piece type="pawn" color="white" />,
  ],
  [
    <Piece type="rook" color="white" />,
    <Piece type="knight" color="white" />,
    <Piece type="bishop" color="white" />,
    null,
    <Piece type="king" color="white" />,
    null,
    <Piece type="knight" color="white" />,
    <Piece type="rook" color="white" />,
  ],
];
